import React from "react";
import { Container, Row, Col, Nav, Navbar, Card } from "react-bootstrap";
import Link from "next/link";
import Head from "next/head";
import Script from "next/script";
import data from "./ProjectList.json";

const Projects = () => {
  const projectData = data.projects;
  const projectsList = Object.keys(projectData).map((project) => {
    const projectValue = projectData[project];
    return (
      <Card
        style={{
          paddingTop: "0",
          width: "330px",
          overflowX: "hidden",
          overflowY: "hidden",
          backgroundColor: "white",
        }}
      >
        <Card.Img
          variant="top"
          src={projectValue.image}
          style={{ marginTop: "0", overflow: "hidden" }}
        />
        <div>
          <Card.Body style={{ backgroundColor: "white" }}>
            <Card.Title style={{ backgroundColor: "white", color: "black" }}>
              {projectValue.name}
            </Card.Title>
            {console.log(projectValue.description)}
            <Card.Text style={{ backgroundColor: "white", color: "black" }}>
              {projectValue.description}
            </Card.Text>
            <Card.Link
              style={{ backgroundColor: "white" }}
              href={projectValue.src}
            >
              View Project
            </Card.Link>
          </Card.Body>
        </div>
      </Card>
    );
  });
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossOrigin="anonymous"
      />
      <Container>
        <Row>
          <Col>
            <h1>Projects</h1>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row
              style={{ gap: "50px", marginTop: "20px", marginBottom: "20px" }}
              className="justify-content-center"
            >
              {projectsList}
            </Row>
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default Projects;
