import React from "react";
import { Container, Row, Col, Nav, Navbar } from "react-bootstrap";
import Link from "next/link";
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import { useEffect } from "react";

const Resume = () => {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossOrigin="anonymous"
      />
      <Container
        fluid
        className="aboutMe"
        style={{
          paddingTop: "10vh",
          paddingRight: "10px",
          paddingLeft: "10px",
          width: "100% !important",
          backgroundColor: "#ee6c4d",
          paddingBottom: "20vh",
        }}
      >
        <Row>
          <Col
            className="aboutMeDescription text-center"
            style={{ marginBottom: "20px" }}
          >
            <h1>Experience</h1>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>
              <span style={{ fontWeight: "bold" }}>Web Developer</span> | Blue
              Yonder | 09/2022 - Current
            </h4>
            <ul>
              <li>Developing a new web application for the company</li>
            </ul>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>
              <span style={{ fontWeight: "bold" }}>Finance Manager</span> |
              Ourisman Automotive | 11/2017 - 1/2022
            </h4>
            <ul>
              <li></li>
            </ul>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>
              <span style={{ fontWeight: "bold" }}>
                Manager, Web Developer, and Digital Content Creator
              </span>{" "}
              | Ourisman Automotive | 04/2012 - 11/2017
            </h4>
            <ul>
              <li></li>
            </ul>
          </Col>
        </Row>
        <Row>
          <Col>
            <h4>
              <span style={{ fontWeight: "bold" }}>
                Lead E-commerce Consultant
              </span>{" "}
              | Ourisman Automotive | 05/2011 - 04/2012
            </h4>
            <ul>
              <li></li>
            </ul>
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default Resume;
